### ISSUE TITLE
Discovery: 

### ISSUE THREAD

**Issue by Marwe** [opendata-stuttgart/airrohr-firmware-flasher#13]
I get the following error/traceback while trying to discover sensors:

```
ERROR:root:Unhandled exception
Traceback (most recent call last):
  File "/home/user/soft/luftdaten/airrohr-firmware-flasher/luftdatentool/utils.py", line 32, in run
    self.target(*self.args, **self.kwargs)
  File "/home/user/soft/luftdaten/airrohr-firmware-flasher/luftdatentool/workers.py", line 47, in target
    self.zc = zeroconf.Zeroconf()
  File "/home/user/.virtualenvs/airrohr-firmware-flasher/local/lib/python3.6/site-packages/zeroconf.py", line 1696, in __init__
    socket.inet_aton(_MDNS_ADDR) + socket.inet_aton(i))
OSError: [Errno 105] No buffer space available
```

Any idea what this is about or if I am missing something on my system?
"buffer space missing" sounds like hardware/driver issues to me, as if it is about allocation by the system.

I tried the following solution unsuccessfully (on Ubuntu 18.04):
https://stackoverflow.com/questions/46727211/oserror-105-no-buffer-space-zeroconf

```
sudo -i
echo 20 >/proc/sys/net/ipv4/igmp_max_memberships
echo 10 >/proc/sys/net/ipv4/igmp_max_msf
systemctl restart avahi-daemon
```

Any more things that could be tried?

**Comment by Marwe** [comment]
Finally works fine, both .py and compiled version.
