### ISSUE TITLE
Error when using undescore character in build name

### ISSUE THREAD

**Issue by DeeKey** [opendata-stuttgart/airrohr-firmware-flasher#19]
Rename the build file name to include underscore sign.
Flashing will not start. There will be an error:

Traceback (most recent call last):
  File "/home/informatic/Projects/luftdaten-tools/luftdatentool/utils.py", line 32, in run
  File "/home/informatic/Projects/luftdaten-tools/luftdaten-tool.py", line 259, in flash_board
AttributeError: 'NoneType' object has no attribute 'startswith'
ERROR:root:Unhandled exception
Traceback (most recent call last):
  File "/home/informatic/Projects/luftdaten-tools/luftdatentool/utils.py", line 32, in run
  File "/home/informatic/Projects/luftdaten-tools/luftdaten-tool.py", line 259, in flash_board
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by Informatic** [comment]
`latest_en.bin` binary from default list is downloaded properly on Linux. What platform are you using?
